name: Build and Deploy Test

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.7
        
    - name: Build and Test
      run: |
        cd CSharpTest
        dotnet build CSharpTest.sln
        dotnet test ./UnitTestProject1/UnitTestProject1.csproj

    - name: Merge commit message
      run: |
        git log -1 --pretty=%B > message.txt
        echo "::set-output name=message::$(cat message.txt)"
      id: merge_message

    - name: Create release tag
      if: startsWith(steps.merge_message.outputs.message, 'Release')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.merge_message.outputs.message }}
        release_name: Release ${{ steps.merge_message.outputs.message }} - ${{ github.sha }}
        body: ${{ steps.merge_message.outputs.message }}
        draft: false
        prerelease: false
        
    - name: Deploy to production
      if: startsWith(steps.merge_message.outputs.message, 'Release')
      run: |
        echo "End All"
